package br.uff.diogo.lp.gui;

import br.uff.diogo.lp.animais.AnimalManager;
import br.uff.diogo.lp.funcionarios.FuncionarioManager;
import br.uff.diogo.lp.util.TipoAnimal;

public class CadastroAnimal extends javax.swing.JFrame {
    
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

    /**
     * Creates new form CadastroFelino
     */
    
    public CadastroAnimal(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboEspecie = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboCuidador = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel3.setText("Especie:");

        cboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguia", "Arara", "Falcao", "Elefante", "Leao", "Macaco", "Lagarto", "Jacare", "Cobra"}));
        cboEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEspecieActionPerformed(evt);
            }
        });

        jLabel4.setText("Funcionario:");
        
        cboCuidador.setModel(new javax.swing.DefaultComboBoxModel<String>(FuncionarioManager.getNomes()));

        jLabel6.setText("Peso:");

        btnGravar.setText("Gravar");
        btnGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboEspecie, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE)
                                .addComponent(cboCuidador, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmpNome)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnGravar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /*for(Cuidador c : Bd.listaCuidador){
            cboCuidador.addItem(c);
        }*/
        cboEspecie.setSelectedItem(null);
    }//GEN-LAST:event_formWindowActivated

    private void btnGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarMouseClicked
        //Mamifero f = new Mamifero();
        
    	if(cmpNome.getText() == null || cboCuidador.getSelectedItem() == null || cboEspecie.getSelectedItem()==null)return;
    	
    	AnimalManager.adicionarAnimal(cmpNome.getText(), FuncionarioManager.getFuncionario((String)cboCuidador.getSelectedItem()), TipoAnimal.valueOf(((String)cboEspecie.getSelectedItem()).toUpperCase()));
    	this.setVisible(false);
    	this.dispose();

    }//GEN-LAST:event_btnGravarMouseClicked

    private void cboEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEspecieActionPerformed
    	if(cboEspecie.getSelectedItem()==null) {
    		txtPeso.setText("0");
    		txtPeso.setEnabled(false);
    		return;
    	}
    	
        if(cboEspecie.getSelectedItem().equals("Elefante")){
            txtPeso.setText("6000");
        }
        
        if(cboEspecie.getSelectedItem().equals("Leao")){
            txtPeso.setText("170");
        }
        
        if(cboEspecie.getSelectedItem().equals("Macaco")){
            txtPeso.setText("40");
        }
        
        if(cboEspecie.getSelectedItem().equals("Arara")){
            txtPeso.setText("2");
        }
        
        if(cboEspecie.getSelectedItem().equals("Aguia")){
            txtPeso.setText("7");
        }
        
        if(cboEspecie.getSelectedItem().equals("Falcao")){
            txtPeso.setText("5");
        }
        
        if(cboEspecie.getSelectedItem().equals("Cobra")){
            txtPeso.setText("2");
        }
        
        if(cboEspecie.getSelectedItem().equals("Jacare")){
            txtPeso.setText("70");
        }
        
        if(cboEspecie.getSelectedItem().equals("Lagarto")){
            txtPeso.setText("3");
        }
        
        txtPeso.setEnabled(false);
    }//GEN-LAST:event_cboEspecieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<String> cboCuidador;
    private javax.swing.JComboBox<String> cboEspecie;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
