package br.uff.diogo.lp.gui;

import br.uff.diogo.lp.funcionarios.Funcionario;
import br.uff.diogo.lp.funcionarios.FuncionarioManager;
import br.uff.diogo.lp.util.TipoAnimal;
import br.uff.diogo.lp.util.TipoFuncionario;

public class CadastroFuncionario extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	boolean editando;

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
        editando = false;
        txtID.setText(String.valueOf(FuncionarioManager.getIdGlobal()));
        txtID.setEnabled(false);
    }
    
    public CadastroFuncionario(Funcionario f, boolean cuidador) {
        initComponents();
        editando = true;
        txtID.setText(String.valueOf(f.getID()));
        txtID.setEnabled(false);
        txtNome.setText(f.getNome());
        txtSal.setText(String.valueOf(f.getSalario()));
        if(cuidador) {
        	cboFunc.setSelectedItem("Cuidador");
        }else {
        	cboFunc.setSelectedItem("Veterinario");
        }
        cboFunc.setEnabled(false);
        cboEspe.setSelectedItem(f.getEspecializacao().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        lblEspe = new javax.swing.JLabel();
        cboEspe = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSal = new javax.swing.JTextField();
        lblVariavel = new javax.swing.JLabel();
        rdoSim = new javax.swing.JRadioButton();
        rdoNao = new javax.swing.JRadioButton();
        btnGravar = new javax.swing.JButton();
        lblFunc = new javax.swing.JLabel();
        cboFunc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblID.setText("ID:");

        lblNome.setText("Nome:");

        lblSal.setText("Salario:");

        lblEspe.setText("Especializacao:");

        cboEspe.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Aguia", "Arara", "Falcao", "Elefante", "Leao", "Macaco", "Cobra", "Lagarto", "Jacare" }));

        lblVariavel.setText("Equipamentos:");

        rdoSim.setText("Sim");

        rdoNao.setText("Nao");

        btnGravar.setText("Gravar");
        btnGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarMouseClicked(evt);
            }
        });

        lblFunc.setText("Funcao:");

        cboFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuidador", "Veterinario" }));
        cboFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEspe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboEspe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(rdoNao))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFunc))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(txtID)
                                .addComponent(txtSal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSal)
                    .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspe)
                    .addComponent(cboEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVariavel)
                    .addComponent(rdoSim)
                    .addComponent(rdoNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFuncActionPerformed
    	if(cboFunc.getSelectedItem() == null)return;
        if(cboFunc.getSelectedItem().equals("Cuidador")){
            lblVariavel.setText("Brinquedos:");
        }else if(cboFunc.getSelectedItem().equals("Veterinario")){
            lblVariavel.setText("Equipamentos:");
        }
        lblVariavel.setVisible(true);
        rdoSim.setVisible(true);
        rdoNao.setVisible(true);
    }//GEN-LAST:event_cboFuncActionPerformed
        
    private void btnGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarMouseClicked
        if(cboEspe.getSelectedItem() == null || cboFunc.getSelectedItem()==null)return;
    	
    	String nome = txtNome.getText();
    	String senha = "3020";
    	int salario = Integer.parseInt(txtSal.getText());
    	TipoAnimal esp = TipoAnimal.valueOf(((String)cboEspe.getSelectedItem()).toUpperCase());
    	TipoFuncionario tipoFun = TipoFuncionario.valueOf(((String)cboFunc.getSelectedItem()).toUpperCase());
    	
        if(editando){
            if(cboFunc.getSelectedItem().equals("Cuidador")){
                FuncionarioManager.editarCuidador(Integer.parseInt(txtID.getText()), nome, salario, esp, rdoSim.isSelected());
            }else if(cboFunc.getSelectedItem().equals("Veterinario")){
                FuncionarioManager.editarVeterinario(Integer.parseInt(txtID.getText()), nome, salario, esp, rdoSim.isSelected());
            }
        }else{
            FuncionarioManager.adicionarFuncionario(nome, senha, salario, esp, tipoFun);	
        }
    	this.setVisible(false);
    	this.dispose();
    }//GEN-LAST:event_btnGravarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(!editando){
            lblVariavel.setVisible(false);
            rdoSim.setVisible(false);
            rdoNao.setVisible(false);
            cboEspe.setSelectedItem(null);
            cboFunc.setSelectedItem(null);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<String> cboEspe;
    private javax.swing.JComboBox<String> cboFunc;
    private javax.swing.JLabel lblEspe;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSal;
    private javax.swing.JLabel lblVariavel;
    private javax.swing.JRadioButton rdoNao;
    private javax.swing.JRadioButton rdoSim;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSal;
    // End of variables declaration//GEN-END:variables
}
