package br.uff.diogo.lp.gui;

import javax.swing.SwingConstants;

import br.uff.diogo.lp.animais.Animal;
import br.uff.diogo.lp.animais.AnimalManager;
        
public class GuiAnimais extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Animais
     */
    public GuiAnimais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAves = new javax.swing.JList<Animal>();
        btnAdd = new javax.swing.JButton();
        btnRem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRepteis = new javax.swing.JList<Animal>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMamiferos = new javax.swing.JList<Animal>();
        lblAves = new javax.swing.JLabel();
        lblRep = new javax.swing.JLabel();
        lblMami = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lstAves.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAvesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAves);

        btnAdd.setText("Adicionar");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnRem.setText("Remover");
        btnRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemMouseClicked(evt);
            }
        });

        lstRepteis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRepteisValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstRepteis);

        lstMamiferos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMamiferosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstMamiferos);

        lblAves.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblAves.setText("Aves");

        lblRep.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblRep.setText("Repteis");

        lblMami.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblMami.setText("<html><div style='text-align: center;'>Mamiferos</div></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblAves, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblMami, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRep, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRep)
                    .addComponent(lblMami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAves))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Trecho pra centralizar as labels
        lblAves.setHorizontalAlignment(SwingConstants.CENTER);
        lblMami.setHorizontalAlignment(SwingConstants.CENTER);
        lblRep.setHorizontalAlignment(SwingConstants.CENTER);
        
        //Pondo os valores nas listas
        lstAves.setListData(AnimalManager.getAves());
        lstMamiferos.setListData(AnimalManager.getMamiferos());
        lstRepteis.setListData(AnimalManager.getRepteis());
        
        
    }//GEN-LAST:event_formWindowActivated

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        new CadastroAnimal().setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnRemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemMouseClicked
        if(!lstMamiferos.isSelectionEmpty()){
        	Animal m = lstMamiferos.getSelectedValue();
            AnimalManager.removeAnimal(m.getNome());
        }
        if(!lstRepteis.isSelectionEmpty()){
        	Animal m = lstRepteis.getSelectedValue();
            AnimalManager.removeAnimal(m.getNome());
        }
        if(!lstAves.isSelectionEmpty()){
        	Animal m = lstAves.getSelectedValue();
            AnimalManager.removeAnimal(m.getNome());
        }
            
        lstMamiferos.setListData(AnimalManager.getMamiferos());
        lstRepteis.setListData(AnimalManager.getRepteis());
        lstAves.setListData(AnimalManager.getAves());
    }//GEN-LAST:event_btnRemMouseClicked

    private void lstAvesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAvesValueChanged
        lstMamiferos.clearSelection();
        lstRepteis.clearSelection();
    }//GEN-LAST:event_lstAvesValueChanged

    private void lstMamiferosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMamiferosValueChanged
        lstAves.clearSelection();
        lstRepteis.clearSelection();
    }//GEN-LAST:event_lstMamiferosValueChanged

    private void lstRepteisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRepteisValueChanged
        lstAves.clearSelection();
        lstMamiferos.clearSelection();
    }//GEN-LAST:event_lstRepteisValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAnimais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAves;
    private javax.swing.JLabel lblMami;
    private javax.swing.JLabel lblRep;
    private javax.swing.JList<Animal> lstAves;
    private javax.swing.JList<Animal> lstMamiferos;
    private javax.swing.JList<Animal> lstRepteis;
    // End of variables declaration//GEN-END:variables
}
