package br.uff.diogo.lp.gui;

import br.uff.diogo.lp.animais.Animal;
import br.uff.diogo.lp.funcionarios.FuncionarioManager;
import br.uff.diogo.lp.animais.AnimalManager;
import br.uff.diogo.lp.funcionarios.Funcionario;

public class GuiEstatisticas extends javax.swing.JFrame {
    

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form GuiEstatisticas
     */
    public GuiEstatisticas() {
        initComponents();
    }
    
    private double getTotalSalario(){
        double totalSalario = 0;
        for(Funcionario f : FuncionarioManager.getListaFuncionarios()){
            totalSalario += f.getSalario();
        }
        return totalSalario;
    }
    
    private double getTotalComida(){
        double totalComida = 0;
        for(Animal a : AnimalManager.getListaAnimais()){
            totalComida += a.getQuantidadeComida();
        }
        return totalComida*30;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAnimais = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaFunc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtAreaAnimais.setColumns(20);
        txtAreaAnimais.setRows(5);
        jScrollPane1.setViewportView(txtAreaAnimais);

        txtAreaFunc.setColumns(20);
        txtAreaFunc.setRows(5);
        jScrollPane2.setViewportView(txtAreaFunc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        double totalSalario = getTotalSalario();
        int qtdFuncionarios = FuncionarioManager.getListaFuncionarios().size();
        String infoFunc = "Temos " + qtdFuncionarios + " funcionarios atualmente, totalizando " + totalSalario + " reais de gasto mensal";
        txtAreaFunc.setLineWrap(true);
        txtAreaFunc.setText(infoFunc);
        
        int qtdAnimais = AnimalManager.getListaAnimais().size();
        double totalComida = getTotalComida();
        String infoAnimais = "Temos " + qtdAnimais + " animais atualmente, totalizando " + totalComida + " kgs de comida gastos mensalmente";
        txtAreaAnimais.setLineWrap(true);
        txtAreaAnimais.setText(infoAnimais);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEstatisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaAnimais;
    private javax.swing.JTextArea txtAreaFunc;
    // End of variables declaration//GEN-END:variables
}
