 package br.uff.diogo.lp.gui;

import br.uff.diogo.lp.funcionarios.*;
import br.uff.diogo.lp.funcionarios.FuncionarioManager;
import br.uff.diogo.lp.funcionarios.Veterinario;

public class GuiFuncionarios extends javax.swing.JFrame {
    

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form teste
     */
    public GuiFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCui = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCuidadores = new javax.swing.JList<Funcionario>();
        btnRem = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        lblVet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVeterinarios = new javax.swing.JList<Funcionario>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblCui.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblCui.setText("Cuidadores");

        btnEdit.setText("Editar");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        lstCuidadores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCuidadoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCuidadores);

        btnRem.setText("Remover");
        btnRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemMouseClicked(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });

        lblVet.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblVet.setText("Veterinarios");

        lstVeterinarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVeterinariosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstVeterinarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblCui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVet, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCui))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCuidadoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCuidadoresValueChanged
        lstVeterinarios.clearSelection();
    }//GEN-LAST:event_lstCuidadoresValueChanged

    private void lstVeterinariosValueChanged(javax.swing.event.ListSelectionEvent evt) {                                             
        lstCuidadores.clearSelection();
    }
    
    private void btnRemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemMouseClicked
    	Funcionario f = null;
        if(!lstCuidadores.isSelectionEmpty()){
            f = (Cuidador)lstCuidadores.getSelectedValue();
            FuncionarioManager.removeFuncionario(f.getID());
        }else if(!lstVeterinarios.isSelectionEmpty()){
            f = (Funcionario)lstVeterinarios.getSelectedValue();
            FuncionarioManager.removeFuncionario(f.getID());
        }
        
        lstCuidadores.setListData(FuncionarioManager.getCuidadores());
        lstVeterinarios.setListData(FuncionarioManager.getVeterinarios());
    }//GEN-LAST:event_btnRemMouseClicked

                                                

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        new CadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        Funcionario f = null;
        boolean cuidador = false;
        if(!lstCuidadores.isSelectionEmpty()){
            //f = FuncionarioManager.getFuncionario((String)lstCuidadores.getSelectedValue());
            f = (Cuidador)lstCuidadores.getSelectedValue();
            cuidador = true;
        }else if(!lstVeterinarios.isSelectionEmpty()){
            //f = FuncionarioManager.getFuncionario((String)lstVeterinarios.getSelectedValue());
            f = (Veterinario)lstVeterinarios.getSelectedValue();
        }
        
        //if(f==null)return;
        
        new CadastroFuncionario(f, cuidador).setVisible(true);
    }//GEN-LAST:event_btnEditMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lstCuidadores.setListData(FuncionarioManager.getCuidadores());
        lstVeterinarios.setListData(FuncionarioManager.getVeterinarios());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCui;
    private javax.swing.JLabel lblVet;
    private javax.swing.JList<Funcionario> lstCuidadores;
    private javax.swing.JList<Funcionario> lstVeterinarios;
    // End of variables declaration//GEN-END:variables
}
